name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.x.x
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - uses: supabase/setup-cli@v1
        with:
          version: 1.83.7
      - run: pnpm install
      - run: supabase db start
      - run: supabase db reset
      - run: |
          supabase status | node parse_status.js | while read line
          do
            echo $line >> "$GITHUB_ENV"
          done
          echo $VITE_SUPABASE_URL
          pnpm test
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.83.7
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.x.x
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - run: pnpm install
      - run: supabase db start
      - run: supabase db reset
      - name: Verify generated types match Postgres schema
        run: |
          supabase gen types typescript --local > src/lib/supabase.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/lib/supabase.ts; then
              echo "Detected uncommitted changes after build. See status below:"
              git diff
              exit 1
          fi
